- hosts: galaxyservers
  become: true
  vars:
    role_debug: true
    galaxy_prefix: ":80"
    galaxy_flavors_recipes_url: 'https://github.com/pmandreoli/Galaxy-flavors-recipes.git'
  roles:
    - ../ansible-role-laniakea-galaxy-tools
  pre_tasks:
    - name: update conda
      systemd:
        name: "{{ item }}"
        state: started
        enabled: True
      with_items:
        - postgresql-10
        - nginx
        - galaxy
