---
- hosts: galaxyservers
  become: true
  tasks:

    - name: install pigz 
      yum:
        name: pigz

    - name: run script for package-creation
      script: 
        cmd: dump.sh -f "{{ galaxy_flavor }}" -v "{{ galaxy_flavor_version }}" -i "{{ image }}"
      args:
        executable: bash
