---
- name: upload package on swift
  hosts: galaxyservers
  become: true
  tasks:

    - name: upgrade pip        
      pip:
        name: pip
        state: latest

    - name: install swift cli        
      pip:
        name: [ "setuptools_rust","python-openstackclient","python-swiftclient" ]

    - name: copy credentials
      copy:
        src: rc.sh 
        dest: /tmp/dump/rc.sh

    - name: upload package on the galaxy_flavors swift container 
      shell: source /tmp/dump/rc.sh && /usr/local/bin/swift upload -S 1073741824  --insecure galaxy_flavors galaxy-express*
      args:
        chdir: /tmp/dump

    



          
            
