# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      Flavor:
        description: 'galaxy flavor to build'     
        required: true
        default: 'galaxy-testing'
      Version: 
        description: 'flavor version'
        required: true
        default: '1'
      Image: 
        description: 'image to use to build the package'
        required: true
        default: 'galaxy-express_v3.0.2'

  # Allows you to run this workflow manually from the Actions tab
  #  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        env:
          JnkUser: ${{ secrets.JnkUser }}
          JnkApiKey: ${{ secrets.JnkApiKey }}
        run: |
          curl -X POST "https://${{ secrets.JnkUser }}:${{ secrets.JnkApiKey }}@build-usegalaxy-it.cloud.ba.infn.it/jenkins/job/flavour_packages_pipeline/buildWithParameters?token=${{ secrets.Token }}&FLAVOR=${{ github.event.inputs.Flavor }}&VERSION=${{ github.event.inputs.Version }}&IMAGE=${{ github.event.inputs.Image }}"

